config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  mount Sidekiq::Web => '/sidekiq'
  # Defines the root path route ("/")
  root "home#index"
  get 'cache/index'
  get 'search/search'
  get 'main/index'

  resources :posts
  resources :songs
  resources :articles
  resources :notifications

  namespace :api do 
    namespace :v1 do 
      resources :clients do 
        collection do 
          get "get_clients"
        end
      end
    end
  end
end

app/models/author.rb
class Author < ApplicationRecord
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
    has_one :author
    has_many :reviews
end

app/models/client.rb
class Client < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :first_name, format: { with: /\A[a-zA-Z]+\z/ }
    validates :last_name, format: { with: /\A[a-zA-Z]+\z/ }
    validates :first_name, length: { minimum:3, maximum:20 }
    validates :last_name, length: { minimum:3, maximum:20 }
    validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 18, less_than_or_equal_to: 30 }
    validates :email, presence: true, on: :update
    validates :email, uniqueness: { case_sensitive: false }, on: :update
    validates :joined_date, comparison: { greater_than: Time.now - 100 }
    validates :country, inclusion: { in: %w(usa india canada australia) }
    validates :country, exclusion: { in: %w(russia ukraine), message: "%{value} seems wrong" }

    scope :active_clients, -> { where(active: true) }
    scope :in_active_clients, -> { where(active: false) }
    scope :clients_by_country, -> (country_name) { where(country: country_name.downcase.to_s) }
    scope :categories_age, -> (min,max) { where("age > :min OR age < :max", { min: min, max: max }) }

    enum :status, [:joined, :releaved]

    before_save do 
        puts "before-save has been called"
    end
    
    before_create do 
        puts "before-create has been called"
    end

    before_update do 
        puts "before-update has been called"
    end

    before_destroy do 
        puts "before-destroy has been called"
    end

    after_save do 
        puts "after-save has been called"
    end

    after_create do 
        puts "after-create has been called"
    end

    after_update do 
        puts "after-update has been called"
    end

    after_destroy do 
        puts "after-destroy has been called"
    end

    after_commit do 
        puts "after-commit has been called"
    end
    
end

app/models/course.rb
class Course < ApplicationRecord
    has_and_belongs_to_many :student
end

app/models/dev.rb
class Dev < Worker
end

app/models/entry.rb
class Entry < ApplicationRecord
    delegated_type :entryable, types: %w[ Message Log ], dependent: :destroy
end

app/models/lead.rb
class Lead < Worker
end

app/models/log.rb
class Log < ApplicationRecord
    include Entryable
end

app/models/notification.rb
class Notification < ApplicationRecord
    searchkick
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :reviewer
end

app/models/parent.rb
class Parent < ApplicationRecord
  belongs_to :player
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :product, touch: true
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_one :parent
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    accepts_nested_attributes_for :comments
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  has_many :reviewers
end

app/models/song.rb
class Song < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
    has_and_belongs_to_many :employees
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :players
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    has_many :employee_tickets
    has_many :employees, through: :employee_tickets
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :validatable,         
         :omniauthable, omniauth_providers: [:google_oauth2, :oktaoauth]

  devise :trackable, :timeoutable, :timeout_in => 60.minutes

   def self.from_omniauth(response)
    user = User.where(email: response[:info]['email']).first

    User.find_or_create_by(email: response[:info][:email]) do |u|
      u.first_name = response[:info][:first_name],
      u.last_name = response[:info][:last_name],
      u.password = Devise.friendly_token[0,20],
      u.uid = response[:uid],
      u.provider = response[:provider]
    end
  end
end

app/models/worker.rb
class Worker < ApplicationRecord
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: %i[ show edit update destroy ]

  # GET /notifications or /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1 or /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications or /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to notification_url(@notification), notice: "Notification was successfully created." }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1 or /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to notification_url(@notification), notice: "Notification was successfully updated." }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1 or /notifications/1.json
  def destroy
    @notification.destroy!

    respond_to do |format|
      format.html { redirect_to notifications_url, notice: "Notification was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notification_params
      params.require(:notification).permit(:title, :content)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_with(model: notification) do |form| %>
  <% if notification.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
        <% notification.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/notifications/_notification.html.erb
<div id="<%= dom_id notification %>">
  <p>
    <strong>Title:</strong>
    <%= notification.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= notification.content %>
  </p>

</div>

app/views/notifications/_notifications.html.erb
<% notifications.each do |notification| %>
    <%= render notification %>
    <p>
      <%= link_to "Show this notification", notification %>
    </p>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render "form", notification: @notification %>

<br>

<div>
  <%= link_to "Show this notification", @notification %> |
  <%= link_to "Back to notifications", notifications_path %>
</div>

app/views/notifications/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Notifications</h1>

<%= form_with url: search_search_path, method: :get do |form| %>
  <%= form.label :search %>
  <%= form.text_field :search %>
  <%= form.submit "Submit" %>
<% end %>

<div id="notifications">
  <%= render "notifications/notifications", notifications: @notifications %>
</div>

<%= link_to "New notification", new_notification_path %>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render "form", notification: @notification %>

<br>

<div>
  <%= link_to "Back to notifications", notifications_path %>
</div>

app/views/notifications/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @notification %>

<div>
  <%= link_to "Edit this notification", edit_notification_path(@notification) %> |
  <%= link_to "Back to notifications", notifications_path %>

  <%= button_to "Destroy this notification", @notification, method: :delete %>
</div>