config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  mount Sidekiq::Web => '/sidekiq'
  # Defines the root path route ("/")
  root "home#index"
  get 'cache/index'
  get 'search/search'
  get 'main/index'

  resources :posts
  resources :songs
  resources :articles
  resources :notifications

  namespace :api do 
    namespace :v1 do 
      resources :clients do 
        collection do 
          get "get_clients"
        end
      end
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/author.rb
class Author < ApplicationRecord
  belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
    has_one :author
    has_many :reviews
end

app/models/client.rb
class Client < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :first_name, format: { with: /\A[a-zA-Z]+\z/ }
    validates :last_name, format: { with: /\A[a-zA-Z]+\z/ }
    validates :first_name, length: { minimum:3, maximum:20 }
    validates :last_name, length: { minimum:3, maximum:20 }
    validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 18, less_than_or_equal_to: 30 }
    validates :email, presence: true, on: :update
    validates :email, uniqueness: { case_sensitive: false }, on: :update
    validates :joined_date, comparison: { greater_than: Time.now - 100 }
    validates :country, inclusion: { in: %w(usa india canada australia) }
    validates :country, exclusion: { in: %w(russia ukraine), message: "%{value} seems wrong" }

    scope :active_clients, -> { where(active: true) }
    scope :in_active_clients, -> { where(active: false) }
    scope :clients_by_country, -> (country_name) { where(country: country_name.downcase.to_s) }
    scope :categories_age, -> (min,max) { where("age > :min OR age < :max", { min: min, max: max }) }

    enum :status, [:joined, :releaved]

    before_save do 
        puts "before-save has been called"
    end
    
    before_create do 
        puts "before-create has been called"
    end

    before_update do 
        puts "before-update has been called"
    end

    before_destroy do 
        puts "before-destroy has been called"
    end

    after_save do 
        puts "after-save has been called"
    end

    after_create do 
        puts "after-create has been called"
    end

    after_update do 
        puts "after-update has been called"
    end

    after_destroy do 
        puts "after-destroy has been called"
    end

    after_commit do 
        puts "after-commit has been called"
    end
    
end

app/models/course.rb
class Course < ApplicationRecord
    has_and_belongs_to_many :student
end

app/models/dev.rb
class Dev < Worker
end

app/models/entry.rb
class Entry < ApplicationRecord
    delegated_type :entryable, types: %w[ Message Log ], dependent: :destroy
end

app/models/lead.rb
class Lead < Worker
end

app/models/log.rb
class Log < ApplicationRecord
    include Entryable
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :reviewer
end

app/models/parent.rb
class Parent < ApplicationRecord
  belongs_to :player
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :product, touch: true
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_one :parent
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    accepts_nested_attributes_for :comments
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  has_many :reviewers
end

app/models/song.rb
class Song < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
    has_and_belongs_to_many :employees
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :players
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    has_many :employee_tickets
    has_many :employees, through: :employee_tickets
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :validatable,         
         :omniauthable, omniauth_providers: [:google_oauth2, :oktaoauth]

  devise :trackable, :timeoutable, :timeout_in => 60.minutes

   def self.from_omniauth(response)
    user = User.where(email: response[:info]['email']).first

    User.find_or_create_by(email: response[:info][:email]) do |u|
      u.first_name = response[:info][:first_name],
      u.last_name = response[:info][:last_name],
      u.password = Devise.friendly_token[0,20],
      u.uid = response[:uid],
      u.provider = response[:provider]
    end
  end
end

app/models/worker.rb
class Worker < ApplicationRecord
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: %i[ show edit update destroy ]

  # GET /songs or /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to song_url(@song), notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to song_url(@song), notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy!

    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:name, :type, :singer)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_with(model: song) do |form| %>
  <% if song.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.text_field :type %>
  </div>

  <div>
    <%= form.label :singer, style: "display: block" %>
    <%= form.text_field :singer %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/songs/_song.html.erb
<div id="<%= dom_id song %>">
  <p>
    <strong>Name:</strong>
    <%= song.name %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= song.type %>
  </p>

  <p>
    <strong>Singer:</strong>
    <%= song.singer %>
  </p>

</div>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render "form", song: @song %>

<br>

<div>
  <%= link_to "Show this song", @song %> |
  <%= link_to "Back to songs", songs_path %>
</div>

app/views/songs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Songs</h1>

<div id="songs">
  <% @songs.each do |song| %>
    <%= render song %>
    <p>
      <%= link_to "Show this song", song %>
    </p>
  <% end %>
</div>

<%= link_to "New song", new_song_path %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render "form", song: @song %>

<br>

<div>
  <%= link_to "Back to songs", songs_path %>
</div>

app/views/songs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @song %>

<div>
  <%= link_to "Edit this song", edit_song_path(@song) %> |
  <%= link_to "Back to songs", songs_path %>

  <%= button_to "Destroy this song", @song, method: :delete %>
</div>